COMPANY_URL_SEGMENTS = {
    "3play": "3play-media",
    "anduril": "andurilindustries",
    "anthropic": "anthropicresearch",
    "astrazeneca": "astrazeneca",
    "basecamp": "basecamp-franchising",
    "bill": "bill",
    "canonical": "canonical",
    "epic": "epic1979",
    "figma": "figma",
    "github": "github",
    "jobnimbus": "jobnimbus",
    "lambda": "lambda-cloud",
    "lucid": "lucidsoftware",
    "mercury": "mercuryhq",
    "minware": "minware",
    "redcat": "red-cat",
    "schoolai": "getschoolai",
    "speechify": "speechifyinc",
    "splitwise": "splitwise-inc-",
    "strider": "teamstrider",
    "underarmour": "under-armour",
    "weave": "getweave"
}